Repository Arquisoft/lomap_es5a, pull requests merged in 2023-03, with the labels that each got.

#101 Corrección dependencias webapp + React 18
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/asides/AccountAside.tsx
  webapp/src/components/asides/accountAside/BottomAccountAside.tsx
  webapp/src/components/asides/accountAside/TopAccountAside.tsx
  webapp/src/components/asides/accountAside/topAccountAside/TopAsideButton.tsx
  webapp/src/pages/saved/SavedPointsPage.tsx
  webapp/src/public/css/components/asides/AccountAside.css
  webapp/src/public/css/components/asides/accountAside/BottomAccountAside.css
  webapp/src/public/css/components/asides/accountAside/TopAccountAside.css
  webapp/src/public/css/components/asides/accountAside/topAccountAside/TopAsideButton.css
  webapp/src/public/css/layouts/accountLayout/AccountLayout.scss
  webapp/tsconfig.json
Labels: 🔨 fix, ✨front-end

#121 Integración trabajo Marcos en rama general Backend
  restapi/controllers/point.controller.ts
  restapi/models/point.model.ts
  restapi/routes/point.route.ts
  restapi/services/helper/hellpers.ts
  restapi/services/point.service.ts
Labels: 🔨 fix, 🍳 back-end, 🎈feature

#129 Cambios en front-end
  webapp/src/components/maps/DragableMarker.tsx
  webapp/src/components/maps/MapWithDragableMarker.tsx
  webapp/src/components/menus/IconMenuItem.tsx
  webapp/src/helpers/MenuHelper.ts
  webapp/src/pages/saved/SavedPointsPage.tsx
  webapp/src/public/css/components/maps/MapWithDragableMark.css
  webapp/src/public/css/components/maps/MapWithDragableMark.css.map
  webapp/src/public/css/components/maps/MapWithDragableMark.scss
  webapp/src/routes/index.ts
  webapp/src/store/miscelanea.store.ts
Labels: ✨front-end

#132 feat: mostrando todos los puntos disponibles en el mapa
  webapp/src/api/api.ts
  webapp/src/components/asides/accountAside/TopAccountAside.tsx
  webapp/src/components/maps/BaseMap.tsx
  webapp/src/components/maps/popups/BaseMapPopup.tsx
  webapp/src/helpers/AuthHelper.ts
  webapp/src/pages/home/HomePage.tsx
Labels: 🎈feature
